<a href="https://colab.research.google.com/github/MarceloApala/IntroductionPython/blob/master/Python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python basics

On this notebook, we will cover the basics of Python and how to make use of different structures $x^2 = y^2+z^2$

In [ ]:
hola = 'hola mundo'
hola

'hola mundo'

In [ ]:
a = 3
b = 0.5
c = True
d = 'Esta es una cadena'

print(a)
print(b)
print(c)
print(d)

3
0.5
True
Esta es una cadena


In [ ]:
type(d)

str

In [ ]:
a = 5
b = 2
c = a / b
d = a // b

print(c)
print(d)

2.5
2


In [ ]:
a = 2
a ** 3

8

Given a = 2, b = 3, c = 4. Perform the following math operations:

\begin{align*}
\large
d = \frac{a^2-b^2+ab}{1-a-b}
\end{align*}

\begin{align*}
\large
x = {\frac{a^3-b^3+c^4}{a^2+b^2+c^3}}
\end{align*}

\begin{align*}
\large
y = \frac{1}{a}+\frac{1}{b^2}+\frac{b}{c}
\end{align*}

Whan happens when we carry out operations with boolean variables? Report to the class. You can use the next cell or create your own

In [ ]:
a = 2
b = 3
c = 4

d = (a ** 2 - b ** 2 + a * b) / (1 - a - b)
d

-0.25

In [ ]:
a = 2
b = 3

if a < b:
    print('a es menor que b')
else:
    print('a no es menor que b')

a es menor que b


In [ ]:
i = 1

while i <= 10:
    print('El valor de i es %i' % i)
    #i = i + 1
    i += 1

El valor de i es 1
El valor de i es 2
El valor de i es 3
El valor de i es 4
El valor de i es 5
El valor de i es 6
El valor de i es 7
El valor de i es 8
El valor de i es 9
El valor de i es 10


In [ ]:
for i in range(1, 21, 2):
    print("Counting %i" % i)

Counting 1
Counting 3
Counting 5
Counting 7
Counting 9
Counting 11
Counting 13
Counting 15
Counting 17
Counting 19


In [ ]:
a = [1, 2, 3, 4, 5]
a[4]

5

In [ ]:
len(a)

5

In [ ]:
b = [[1, 2, 3],
     [4, 5, 6]]

b[0][2]

3

In [ ]:
c = [[1, 2, 3, 4, 5], 
     [6, 7, 8, 9, 10], 
     ['Hello', 'Univalle']]
     
print(c[2][1])

Univalle


In [ ]:
c = [10, 20, 30, 40, 50] + [12] + [13, 14]
c

[10, 20, 30, 40, 50, 12, 13, 14]

In [ ]:
hola = 'hola '
mundo = 'mundo'
hola_mundo = hola + mundo
hola_mundo

'hola mundo'

In [ ]:
c.append(20)
c

[10, 20, 30, 40, 50, 12, 13, 14, 20]

In [ ]:
c.append([5, 10, 15])
c

[10, 20, 30, 40, 50, 12, 13, 14, 20, [5, 10, 15]]

In [ ]:
c.extend([100, 200])
c

[10, 20, 30, 40, 50, 12, 13, 14, 20, [5, 10, 15], 100, 200]

- enumerate
- zip
- dicts
- functions

In [ ]:
listado = [10, 20, 30, 40, 50]
len(listado)

5

In [ ]:
for indice, valor in enumerate(listado):
  print('Indice: %i, valor: %i' % (indice, valor))

Indice: 0, valor: 10
Indice: 1, valor: 20
Indice: 2, valor: 30
Indice: 3, valor: 40
Indice: 4, valor: 50


In [ ]:
dias = [1, 2, 3, 4, 5]
literales = ['lunes', 'martes', 'miercoles', 'jueves', 'viernes']

for elemento in zip(dias, literales):
    print(elemento)

(1, 'lunes')
(2, 'martes')
(3, 'miercoles')
(4, 'jueves')
(5, 'viernes')


In [ ]:
dic = {'lunes': 'Monday', 'martes': 'Tuesday', 'miercoles': 'Wednesday', 4: 'Thursday'}
dic[4]

'Thursday'

In [ ]:
dic['viernes'] = 'Friday'
dic

{4: 'Thursday',
 'lunes': 'Monday',
 'martes': 'Tuesday',
 'miercoles': 'Wednesday',
 'viernes': 'Friday'}

In [ ]:
for llave, valor in dic.items():
  print('Llave: %s, Valor: %s' % (llave, valor))

Llave: lunes, Valor: Monday
Llave: martes, Valor: Tuesday
Llave: miercoles, Valor: Wednesday
Llave: 4, Valor: Thursday
Llave: viernes, Valor: Friday


In [ ]:
def suma(valor1, valor2):
    resultado = valor1 + valor2
    return resultado

In [ ]:
suma(3, 2)

5

# Class declarations


In [ ]:
class Pencil:
    def __init__(self, color, width, brand):
        self.color = color
        self.width = width
        self.brand = brand

    def write(self):
        self.dummy()
        print('Writing...')

    def erase(self):
        print('Erasing...')

    def dummy(self):
        print('This is a dummy method')

    def show_parameters(self):
        print('Color: %s, Width: %s, Brand: %s' % (self.color, self.width, self.brand))

In [ ]:
pencil1 = Pencil('Black', 'HB', 'Faber Castell')
pencil1.show_parameters()

Color: Black, Width: HB, Brand: Faber Castell


In [ ]:
pencil1.write()

This is a dummy method
Writing...


In [ ]:
pencil1.dummy()

This is a dummy method


In [ ]:
pencil1.erase()

Erasing...


In [ ]:
class Person:
    def __init__(self, id, first_name, last_name):
        self._id = id
        self._first_name = first_name
        self._last_name = last_name

    def show_personal_data(self):
        print('ID: %s, First name: %s, Last name: %s' % (self._id, self._first_name, self._last_name))

In [ ]:
person1 = Person('1234', 'Juan', 'Perez')
person1.show_personal_data()

ID: 1234, First name: Juan, Last name: Perez


In [ ]:
class Student(Person):
    def __init__(self, id, first_name, last_name, semester):
        super(Student, self).__init__(id, first_name, last_name)
        self.__semester = semester

    def show_personal_data(self):
        print('ID: %s, First name: %s, Last name: %s, Semester: %i' 
              % (self._id, self._first_name, self._last_name, self.__semester))

In [ ]:
student1 = Student('5432', 'Roberto', 'Flores', 3)
student1.show_personal_data()

ID: 5432, First name: Roberto, Last name: Flores, Semester: 3


# NumPY and Matplotlib introduction

In [ ]:
import numpy as np

In [ ]:
mat1 = np.array([[4,8,4],
                 [3,1,2]])
mat2 = np.array([[8,0,2],
                 [1,-1,3]])

In [ ]:
mat1 + mat2

array([[12,  8,  6],
       [ 4,  0,  5]])

In [ ]:
mat1 - mat2

array([[-4,  8,  2],
       [ 2,  2, -1]])

In [ ]:
mat1 * 2

array([[ 8, 16,  8],
       [ 6,  2,  4]])

In [ ]:
mat1 * mat2

array([[32,  0,  8],
       [ 3, -1,  6]])

In [ ]:
mat1.shape[1]

3

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
A[1, 1]

5

In [ ]:
A[0]

array([1, 2, 3])

In [ ]:
A[0, :]

array([1, 2, 3])

In [ ]:
A[:, 1]

array([2, 5, 8])

In [ ]:
A[0:2, 1]

array([2, 5])

Let:

\begin{align*}
A=\begin{bmatrix}
-1 & 2 & 1 \\
0 & 5 & 2 \\
3 & 2 & 3
\end{bmatrix},
B=\begin{bmatrix}
4 & -1 & 0 \\
1 & 3 & 1 \\
-2 & -1 & 1
\end{bmatrix}
\end{align*}

Perform the following operations:

\begin{align*}
A+2B
\end{align*}
\begin{align*}
B-2A
\end{align*}
\begin{align*}
3AB
\end{align*}
\begin{align*}
A*B
\end{align*}

In [ ]:
import matplotlib.pyplot as plt

from scipy import linalg

In [ ]:
A = np.array([[-1, 0, 2],
              [2, 1, -1],
              [1, 2, 2]])

np.linalg.det(A)

2.0

In [ ]:
B = np.array([[6,-3],
              [-2,1]])

np.linalg.eig(B)

(array([7., 0.]), array([[ 0.9486833 ,  0.4472136 ],
        [-0.31622777,  0.89442719]]))

In [ ]:
np.linalg.matrix_rank(A)

3

In [ ]:
linalg.lu(A)[2]

array([[ 2.        ,  1.        , -1.        ],
       [ 0.        ,  1.5       ,  2.5       ],
       [ 0.        ,  0.        ,  0.66666667]])

In [ ]:
np.diag(A)

array([-1,  1,  2])

In [ ]:
plt.figure(figsize=(5, 5))
plt.